name: hive_repository
description: A dart package that simplifies creating Local Data Sources using Hive.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # analyzer
  dart_code_metrics: ^4.17.1

  hive: ^2.2.2
  synchronized: ^3.0.0+2

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.21.2
  very_good_analysis: "^3.1.0"
